version: '3'
services:
  api:
    build: .
    ports:
      - 3000:3000 
    depends_on:
      - postgres
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/nik -user=postgres -password=postgres_password migrate
    volumes:
      - ./src/migrations/sql:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: nik
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2